### ISSUE TITLE
ToDo before going public

### ISSUE THREAD

**Issue by ciklista** [enowars/enowars4-service-ringring#27]
- [x] add LICENCE (MIT?)

- [x] remove old branches

- [x] `docker-run.sh` still necessary? Should all be possible from the docker-compose file right?

- [x] move test_suite to integration-tests?

- [x] Documentation (both in github and in code)

@FlorianNachtigall
