### ISSUE TITLE
service-ringring todo (until 19.05.)

### ISSUE THREAD

**Issue by FlorianNachtigall** [enowars/enowars4-service-ringring#8]
**Service**
- [x] create flask app
- [x] dockerize app
- [x] provision dockerized postgres db
- [x] add service endpoint for logging / room service invoices
- [x] create drone pipeline job
- [x] checker for exploit # 1
- [ ] checker for exploit # 2
- [ ] add integration tests

**Exploits**
- [x] introduce exploit # 1
- [x] introduce exploit # 2
- [ ] introduce exploit # 3
